---
- name: Install nginx
  apt:
    pkg:
      - nginx-full

- name: enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy the nginx config file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/webapp
    mode: 0644

- name: Create symlink for nginx config
  file:
    src: /etc/nginx/sites-available/webapp
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Remove existing assets directory
  file:
    path: "{{ webapp_root_dir }}"
    state: absent

- name: Create assets directory
  file:
    path: "{{ webapp_root_dir }}"
    state: directory

- name: Copy webapp bundle
  copy:
    src: "{{ webapp_bundle }}"
    dest: /tmp
    mode: 0644

- name: Extract webapp bundle
  command: "tar -C {{ webapp_root_dir }} -xzf /tmp/webapp-bundle.tar.gz"
  warn: false

- name: restart nginx
  service:
    name: nginx
    state: restarted
