[profile.release]
panic = 'unwind'

[workspace]
members = [
    'primitives/core',
    'primitives/ethereum',
    'pallets/bridge',
    'pallets/bridged-asset',
    'pallets/verifier',
    'pallets/polkaeth-app',
    'pallets/polkaerc20-app',
    'node',
    'runtime',
]
