title: Polkadot Ethereum Bridge
email: contact@snowfork.com
description:
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

theme: just-the-docs


aux_links:
  "GitHub":
    - "https://github.com/Snowfork/polkadot-ethereum"

footer_content: "Copyright &copy; 2020 Snowfork"

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
