name: parachain-coverage

on:
  push:
    branches:
      - main
    paths:
      - 'parachain/common/**'
      - 'parachain/node/**'
      - 'parachain/pallets/**'
      - 'parachain/primitives/**'
      - 'parachain/runtime/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('parachain/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true
          target: wasm32-unknown-unknown
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest
          use-tool-cache: true
      - name: Generate code coverage
        run: >-
          cargo +nightly tarpaulin
          --manifest-path parachain/Cargo.toml
          --verbose --workspace --all-features
          --exclude artemis-node,artemis-runtime
          --exclude-files 'node/src/command.rs,*/mock.rs,*/test.rs'
          --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }}
