name: parachain

on:
  push:
    paths:
      - 'parachain/common/**'
      - 'parachain/node/**'
      - 'parachain/pallets/**'
      - 'parachain/primitives/**'
      - 'parachain/runtime/**'
    branches:
      - main
  pull_request:
    paths:
      - 'parachain/common/**'
      - 'parachain/node/**'
      - 'parachain/pallets/**'
      - 'parachain/primitives/**'
      - 'parachain/runtime/**'

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
  build-test-check:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('parachain/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          target: wasm32-unknown-unknown
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path parachain/Cargo.toml
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path parachain/Cargo.toml
