name: release

on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('parachain/Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: parachain/target/release
          key: ${{ runner.os }}-release-target-${{ hashFiles('parachain/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path parachain/Cargo.toml --release
      - uses: actions/upload-artifact@v1
        with:
          name: artemis-node
          path: parachain/target/release/artemis-node